# How to create an Array: 1D

In [2]:
import numpy as np
e = np.array([2,5,7,6])
e

array([2, 5, 7, 6])

In [5]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [7]:
c= np.ones(4)
c

array([1., 1., 1., 1.])

In [13]:
#creating an empty array with 6 elements
d= np.empty(6)
d

array([0., 0., 0., 0., 0., 0.])

In [19]:
#With range of elements
w = np.arange(2)
w

array([0, 1])

In [20]:
#with specific range of elements
x=np.arange(3,30)
x

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [23]:
#continous
y=np.arange(4,9,1)
y

array([4, 5, 6, 7, 8])

In [26]:
#linely spaced array
z=np.linspace(0,10,num=5)
z

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
#specific data type in array
s=np.ones(5, dtype=np.int8)
s

array([1, 1, 1, 1, 1], dtype=int8)

In [35]:
t=np.ones(6, dtype=np.float64)
t

array([1., 1., 1., 1., 1., 1.])

In [ ]:
##Array function
a= np.array([3,9,7,4,10,15,30,27])
a

In [47]:
np.sort(a)

array([ 3,  4,  7,  9, 10, 15, 27, 30])

In [48]:
b= np.array([50,40,10,20,25,15])
b

array([50, 40, 10, 20, 25, 15])

In [49]:
c=np.concatenate((a,b))
c

array([ 3,  9,  7,  4, 10, 15, 30, 27, 50, 40, 10, 20, 25, 15])

In [50]:
np.sort(c)

array([ 3,  4,  7,  9, 10, 10, 15, 15, 20, 25, 27, 30, 40, 50])

# 2D Array

In [39]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [42]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
import numpy as np
x = np.array([[2,3,4],[6,7,8]])
x

array([[2, 3, 4],
       [6, 7, 8]])

In [11]:
y=np.array([[9,7,4],[1,3,6]])
y

array([[9, 7, 4],
       [1, 3, 6]])

In [17]:
y.sum

<function ndarray.sum>

In [18]:
y*5

array([[45, 35, 20],
       [ 5, 15, 30]])

In [19]:
y+9

array([[18, 16, 13],
       [10, 12, 15]])

In [21]:
y.mean()

5.0

In [ ]:
y.s

In [13]:
np.concatenate((x,y),axis=0)

array([[2, 3, 4],
       [6, 7, 8],
       [9, 7, 4],
       [1, 3, 6]])

In [14]:
np.concatenate((x,y),axis=1)

array([[2, 3, 4, 9, 7, 4],
       [6, 7, 8, 1, 3, 6]])

NameError: name 'a' is not defined

# 3D Array

In [45]:
#making and reshape 3D array
np.arange(60).reshape(3,4,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])